apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: iris-classification-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline_compilation_time: '2021-09-15T12:30:41.113173',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "A basic pipeline example
      for iris classification", "name": "iris-classification"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3}
spec:
  entrypoint: iris-classification
  templates:
  - name: condition-1
    dag:
      tasks:
      - {name: train-tree, template: train-tree}
  - name: condition-2
    dag:
      tasks:
      - {name: train-knn, template: train-knn}
  - name: iris-classification
    dag:
      tasks:
      - name: condition-1
        template: condition-1
        when: '{{tasks.train-using-decision-tree.outputs.parameters.train-using-decision-tree-output}}
          >= {{tasks.train-using-k-nearest-neighbors.outputs.parameters.train-using-k-nearest-neighbors-output}}'
        dependencies: [train-using-decision-tree, train-using-k-nearest-neighbors]
      - name: condition-2
        template: condition-2
        when: '{{tasks.train-using-k-nearest-neighbors.outputs.parameters.train-using-k-nearest-neighbors-output}}
          >= {{tasks.train-using-decision-tree.outputs.parameters.train-using-decision-tree-output}}'
        dependencies: [train-using-decision-tree, train-using-k-nearest-neighbors]
      - {name: train-using-decision-tree, template: train-using-decision-tree}
      - {name: train-using-k-nearest-neighbors, template: train-using-k-nearest-neighbors}
  - name: train-knn
    container:
      args: [python3  iris_classification.py save_final_model knn]
      command: [sh, -c]
      image: annajung/iris:latest
    outputs:
      artifacts:
      - {name: train-knn-output, path: /tmp/knn.pkl}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: train-tree
    container:
      args: [python3  iris_classification.py save_final_model tree]
      command: [sh, -c]
      image: annajung/iris:latest
    outputs:
      artifacts:
      - {name: train-tree-output, path: /tmp/tree.pkl}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: train-using-decision-tree
    container:
      args: [python iris_classification.py build_model tree]
      command: [sh, -c]
      image: annajung/iris:latest
    outputs:
      parameters:
      - name: train-using-decision-tree-output
        valueFrom: {path: /tmp/accuracy_tree.txt}
      artifacts:
      - {name: train-using-decision-tree-output, path: /tmp/accuracy_tree.txt}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  - name: train-using-k-nearest-neighbors
    container:
      args: [python iris_classification.py build_model knn]
      command: [sh, -c]
      image: annajung/iris:latest
    outputs:
      parameters:
      - name: train-using-k-nearest-neighbors-output
        valueFrom: {path: /tmp/accuracy_knn.txt}
      artifacts:
      - {name: train-using-k-nearest-neighbors-output, path: /tmp/accuracy_knn.txt}
    metadata:
      labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.6.3, pipelines.kubeflow.org/pipeline-sdk-type: kfp}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner